### ISSUE TITLE
[Linux] Window can still be resized past minimum on Gnome

### ISSUE THREAD

**Issue by lo2dev** [kra-mo/sly#13]
From my understanding, minimum window size should be enforced, but i can still resize the window to the point of being invisible on 0.1.4

https://github.com/user-attachments/assets/8329ce4c-5841-410e-b10a-013d73afa2ec

# System Details Report

## Report details
- **Date generated:**                              2024-09-12 12:53:11
## Software Information:
- **Firmware Version:**                            3404
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.10.8-200.fc40.x86_64

**Comment by kra-mo** [comment]
This is fixed now, but the incorrect version was published to Flathub. If you update, the issue should be resolved.

**Comment by lo2dev** [comment]
Oops literally noticed just now, sorry about that ^^
