### ISSUE TITLE
Replace Export icon

### ISSUE THREAD

**Issue by heldderarbeit** [kra-mo/sly#32]
The name "Export" and the upward pointing arrow on the icon gave me the impression that the functionality is going to upload the finished image to the cloud.

![image](https://github.com/user-attachments/assets/e8226925-db83-4158-81f2-6c7898285a75)

Since only local downloads are allowed, maybe it would be more appropriate to replace the icon with a downward pointing arrow. The original icon could be turned on its head instead (aka "something you download TO your hard drive" instead "FROM your hard drive").

**Comment by kra-mo** [comment]
The icon is the symbol commonly used for sharing. I don’t think it warrants replacement, especially because I will probably allow the use of sharing via the system-wide share menu on mobile platforms in the future.
