### ISSUE TITLE
Android: Small preview

### ISSUE THREAD

**Issue by Grum999** [kra-mo/sly#38]
Hi

Starting to test the **Android** version (v0.3.4 downloaded from Play Store)

One thing I really need when working on photos is to be able to see the photo in full-screen with the ability to zoom in (at least 400%) 

Even if UI is nice and shiny, with Sly I found difficult to really understand what I'm doing on my picture.

# Current use case

1) General UI: the picture is small, settings takes practically all the smartphone screen...
![General UI on Sly](https://github.com/user-attachments/assets/76bef677-69bf-4800-9ccd-d3a8570c3e3e)

2) I do zoom
 - Picture area is the same 
 - Zoom seems to be limited to reach size 1:1 
![General UI on Sly - tried to zoom on picture](https://github.com/user-attachments/assets/381bcbb0-a089-4473-bfac-3a0876aff37d)

> Note: I really have some difficulties to manage zoom with the two finger things (I'll open another issue to explain the case)

# What is expected?

Ideally, having the possibility to work on full-screen picture, without visible UI elements and at least with a 400% Zoom available, would be really nice:
 - I'm more interested by the picture itself than the settings UI elements :-)
 - I can have a good vision/estimation of results
 - Zoom x4 allows me in some case to ensure in small details are Ok

**Comment by alirezaalavi87** [comment]
I wanted to submit this too.

also, do not round the images corners. that might look nice, but from a professional standpoint, the image is a rectangle, so it should be viewed as a rectangle. 
please make the image bigger(from edge to edge), and without rounded corners.

**Comment by kra-mo** [comment]
There will be an option to preview the image full-screen.
