### ISSUE TITLE
Mobile: "Open" icon

### ISSUE THREAD

**Issue by Grum999** [kra-mo/sly#40]
Hi

Testing the Android version (v0.3.4 downloaded from Play Store)

I'm not sure if UI/Icons are the same across all platforms.

# Current use case

The "Plus" button is used to "Open" a document.
![1729268499224](https://github.com/user-attachments/assets/26222404-1a33-4109-9b86-24736f00b156)

I'm aware that many application have a "floating '+' button" we can use to create a new document/action/stuff, but here the "+" button available in toolbar with other tools let user think he will access to additional functionalities/tools to manipulate image; clicking on it open intent to open a document...

# What is expected?
- A more understandable icon ("open folder" or "image icon") 
or
- The "+" button not placed in the toolbar or having a visual information that let no doubt about the fact this button is not an access to additional fuinctionalities/tools

**Comment by kra-mo** [comment]
Thing is, this won't open a file manager, so having it be a folder icon makes less sense to me. In general, I'm pretty limited with the icon dimensions. The idea for the metaphor here is "Add Image" and in the future, I plan on making it possible for multiple images to be editable at the same time.

For the time being, I can see your point but don't think this is an issue as tapping on the button is a fairly inexpensive operation.

**Comment by Grum999** [comment]
ah ok, if [future] implementation is to be able to manage multiple images at the same time, the "+" button make sense :+1: 

That just for now on my side, as it open the file manager on android (at least on my side the intent to open an image is a 'file manger' but maybe it has another name on Android?) and replace current edited image by the selected one so I was thinking it was an "open" button ^_^'

May be the issue can be closed in this case

**Comment by kra-mo** [comment]
Ah right, it depends on your Android ROM. But on iOS for example, it'd be Photos that opens.
