### ISSUE TITLE
Android/iOS: Add adaptive icon

### ISSUE THREAD

**Issue by Penfore** [kra-mo/sly#42]
On Android there are adaptive icons that follows the theme settings of the system.

For example, my theme is set to grey:
![example](https://github.com/user-attachments/assets/012c9063-c167-4d53-8b06-d7ea43be5110)

A monochrome icon is needed to configure this on the project.
Here is the [Android documentation](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) and here is a [Flutter and design guide](https://medium.com/@Toglefritz/add-android-themed-icon-support-to-your-flutter-app-203a7b49d37b).

I normally use the package [flutter_laucnher_icons](https://pub.dev/packages/flutter_launcher_icons) to generate the different icon sizes from one icon file.

It's a simple implementation and I'm available to configure this on the project if anyone is willing to provide the monochrome icon design.

**Comment by kra-mo** [comment]
I'd rather not depend on an external package for this, I can provide a monochrome version myself ^^

**Comment by kra-mo** [comment]
This should also be done for iOS 18.
