### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by KubaUrbanowicz** [kra-mo/sly#44]
Not working on Debian 12 XFCE, standard install. Perhaps an old Nvidia 340 driver gets in the way? To be sure, I can't run recent Gnome versions on my system, so that could be is the reason.
`xxxx@jk24box:~$ flatpak run page.kramo.Sly
Gtk-Message: 22:32:34.788: Failed to load module "xapp-gtk3-module"
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(76)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed`
I don't suppose there is a way around it, is there?
Jakub

**Comment by kra-mo** [comment]
If you can't run recent GNOME versions, there's probably nothing I can do about this. The app has nothing to do with xapp, so I don't think this is a Sly issue, sorry :(
